name: UpgradeImpact hosted test

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  analyse:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: mohdrumman1/upgrade-impact@v1-beta.3
        with:
          github-token: ${{ github.token }}
          hosted-endpoint: ${{ vars.UPGRADE_IMPACT_BETA_ENDPOINT }}
          license-key: ${{ secrets.UPGRADE_IMPACT_BETA_TOKEN }}
